---
title: DH@NCKU-Chemistry
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  news:
    output: true
  publications:
    output: true
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: false
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
  - scope:
      path: ''
      type: pages  # This targets static pages like the home page
    values:
      layout: article  # Replace 'home' with your custom layout if you have one
text_skin: ocean
highlight_theme: tomorrow-night-blue
url: https://dima-huang.github.io/
baseurl:
description: 'The DH Lab

'
lang:
author:
  type:
  name: Your Name
  url:
  avatar:
  bio: I am an amazing person.
  email:
  facebook:
  twitter:
  weibo:
  googleplus:
  telegram:
  medium:
  zhihu:
  douban:
  linkedin:
  github:
  npm:
repository: dima-huang/dima-huang.github.io
repository_tree: main
paths:
  root:
  home:
  archive:
  rss:
excerpt_separator: "<!--more-->"
license: CC-BY-NC-4.0
toc:
  selectors:
mathjax:
mathjax_autoNumber:
mermaid:
chart:
paginate: 8
paginate_path: "/page:num"
sources:
sharing:
  provider: false
  addthis:
    id:
comments:
  provider: false
  disqus:
    shortname:
  gitalk:
    clientID:
    clientSecret:
    repository:
    owner:
    admin:
  valine:
    app_id:
    app_key:
    placeholder:
    visitor:
    meta:
pageview:
  provider: false
  leancloud:
    app_id:
    app_key:
    app_class:
search:
  provider: default
  google:
    custom_search_engine_id:
analytics:
  provider: false
  google:
    tracking_id:
    anonymize_ip: false
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
- CHANGELOG.md
- HOW_TO_RELEASE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- "/docs"
- "/node_modules"
- "/screenshots"
- "/test"
- "/vendor"
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji
